import type { NextPage } from 'next'
import Head from 'next/head'
import { FC, useState } from 'react'
import clsx from 'clsx'


const Home: NextPage = () => {
  const [imageUrl, setImageUrl] = useState('')
  const [showModal, setShowModal] = useState(false)
  const title = `Vivian's Shoppe`;

  const images = [
    '/images/art/froggy.jpg',
    '/images/art/BabyMonkeyPostcard.PNG',
    '/images/art/UtahComic.PNG',
    // '/images/art/VintageRayCommission.jpg'
]

  return (
    <div className="h-full flex flex-col items-center justify-center gap-5 p-20">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/rainbows/rainbow-blue-svgrepo-com.svg" />
      </Head>
      <div className="flex flex-wrap gap-5 w-full justify-center">
          {images.map((image, i) => (
            <Thumbnail src={image} key={i}
              onClick={() => {
                setImageUrl(image)
                setShowModal(true)
            }}
            />
          ))}
          </div>
        <Modal show={showModal} onClose={() => setShowModal(false)} imageUrl={imageUrl}>
          <>
          </>
        </Modal>

    </div>
  )
}

export default Home

const Modal: FC<{show: boolean, onClose: () => void, imageUrl: string}> = ({ show, onClose, children, imageUrl }) => {
  return (
    <div className={clsx("absolute inset-0 justify-center", show ? 'flex' : 'hidden')}>
      <div className="absolute h-full w-full bg-black opacity-40" />
      <div className="absolute bg-transparent rounded-xl inset-0 m-10 flex flex-col bg-contain bg-no-repeat bg-center"  style={{backgroundImage: `url(${imageUrl})`}}>
        {children}
      </div>
        <button  onClick={onClose} className="absolute rounded-xl m-1 w-8 h-8 bg-black justify-center flex items-center">
        <span className="cursor-pointer w-full text-white">X</span>
        </button>
  </div>
  )
}

const Thumbnail: FC<{onClick: () => void; src: string}> = ({ onClick, src }) => {
  return (
    <img
      alt="thumbnail"
      onClick={onClick}
      className="transform hover:scale-125 transition ease-in-out duration-150 cursor-pointer rounded-lg contrast-125 filter"
      height="200"
      width="400"
      src={src}
    />
  )
}
