import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../src/components/layout'

const Home: NextPage = () => {
  return (
    <div className="h-screen bg-green-200">
      <Head>
        <title>Palette Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/rainbows/rainbow-blue-svgrepo-com.svg" />
      </Head>
      <Layout>
      <main> 
        <h1 className="text-9xl"> 
          Welcome to Palette Generator!
        </h1>
      </main>
      </Layout>
    </div>
  )
}

export default Home
