import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../src/components/layout'

const PalettePage: NextPage<APIRequest> = ({data}) => {
  return (
    <div className="h-screen bg-green-200">
      <Head>
        <title>Palette Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/rainbows/rainbow-blue-svgrepo-com.svg" />
      </Head>
      <Layout>
        <main> 
          <h1 className="text-9xl"> 
            Welcome to Palette Generator!
          </h1>
          <div className="flex flex-col items-center">
            {data.result?.map((color: any) => <span key={color}>{color}</span>)}
          </div>
        </main>
      </Layout>
    </div>
  )
}

type APIRequest = {
  data: PaletteJSON
}

type PaletteJSON = {
  result: number[]
}

// This gets called on every request
export async function getServerSideProps() {
  var inputData = {
    model : "default",
    input : [[44,43,44],[90,83,82],"N","N","N"]
  }

  // Fetch data from external API
  const url = "http://colormind.io/api/";
  const res = await fetch(url, {
    method: 'POST',
    body: JSON.stringify(inputData)
  })
  const data = await res.json()

  return { props: { data } }
}

export default PalettePage
