import type { NextPage } from 'next'
import Head from 'next/head'
import tw, { css } from 'twin.macro'
import {useState} from 'react'

const inputData = {
  model : "default",
  input : ["N", "N", "N","N","N"]
}

const PalettePage: NextPage<APIRequest> = ({data}) => {
  const [newData, setNewData] = useState(data)

  const handleClick = async() => {
    // Fetch data from external API
    const url = "http://colormind.io/api/";
    const res = await fetch(url, {
      method: 'POST',
      body: JSON.stringify(inputData)
    })
    const data = await res.json()
  
   setNewData(data)
  }

  const bgColors = (rgbColor: number[]) => css`background-color: rgb(${rgbColor.join(',')})`;
  return (
    <div className="w-full justify-center items-center flex flex-col gap-5">
      <Head>
        <title>Palette Generator</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/images/rainbows/rainbow-blue-svgrepo-com.svg" /> */}
      </Head>
          <h1 className="text-center"> 
           click the button to generate a random color palette 
          </h1>
          <button className="bg-yellow-200 hover:bg-yellow-300 rounded-xl mx-auto p-2" onClick={handleClick}>the button</button>
          <div className="flex flex-col items-center m-2">
            <div className="justify-start">
            {newData.result?.map((color: number[], i: number) =>
            <div key={i} className="flex flex-row">
              <span
                css={[
                  bgColors(color),
                  tw`w-8 h-8 mr-4`,
                ]}
                key={i}
              >
              </span>
              <span>{color.join(', ')}</span>
              </div>
            )}
            </div>
          </div>
    </div>
  )
}

type APIRequest = {
  data: PaletteJSON
}

type PaletteJSON = {
  result: [
    number[]
  ]
}

// This gets called on every request
export async function getServerSideProps() {
  // Fetch data from external API
  const url = "http://colormind.io/api/";
  const res = await fetch(url, {
    method: 'POST',
    body: JSON.stringify(inputData)
  })
  const data = await res.json()

  return { props: { data } }
}

export default PalettePage
